MaterialData:
   - STONE
   - GRASS
   - DIRT
   - COBBLESTONE
   - WOOD
   - BEDROCK
   - SAND
   - GRAVEL
   - GOLD_ORE
   - IRON_ORE
   - COAL_ORE
   - LOG
   - LEAVES
   - SPONGE
   - GLASS
   - LAPIS_ORE
   - LAPIS_BLOCK
   - SANDSTONE
   - NOTE_BLOCK
   - PISTON_STICKY_BASE
   - PISTON_BASE
   - WOOL
   - GOLD_BLOCK
   - IRON_BLOCK
   - BRICK
   - TNT
   - BOOKSHELF
   - MOSSY_COBBLESTONE
   - OBSIDIAN
   - MOB_SPAWNER
   - DIAMOND_ORE
   - DIAMOND_BLOCK
   - WORKBENCH
   - FURNACE
   - REDSTONE_ORE
   - ICE
   - SNOW_BLOCK
   - CACTUS
   - CLAY
   - JUKEBOX
   - PUMPKIN
   - NETHERRACK
   - SOUL_SAND
   - GLOWSTONE
   - JACK_O_LANTERN
   - MONSTER_EGGS
   - SMOOTH_BRICK
   - HUGE_MUSHROOM_1
   - HUGE_MUSHROOM_2
   - MELON_BLOCK
   - MYCEL
   - NETHER_BRICK
   - ENDER_STONE
   - REDSTONE_LAMP_OFF
   - EMERALD_ORE
   - EMERALD_BLOCK
   - COMMAND
   - BEACON
   - REDSTONE_BLOCK
   - QUARTZ_ORE
   - QUARTZ_BLOCK
   - DROPPER
   - STAINED_CLAY
   - LEAVES_2
   - LOG_2
   - HAY_BLOCK
   - HARD_CLAY
   - COAL_BLOCK
   - PACKED_ICE