name: Furniture
version: 0.1
description: DiceEquipment
author: Ste3et_C0st
website: http://dicecraft.de

main: de.Ste3et_C0st.Furniture.Main.main

commands: 
  Furniture:
    description:  test
    usage:  /<command>