name: Furniture
version: 1.5
description: DiceEquipment
author: Ste3et_C0st
website: http://dicecraft.de
softdepend: [Vault]
main: de.Ste3et_C0st.Furniture.Main.main

commands: 
  furniture:
    description:  DiceEaster Egg Command
    usage:  /<command>